Algoritmo "Mod e Div"

Var
  //x,y: inteiro
  //w:real
  x:inteiro


Inicio
    //x <- 10
    //y <- 3
    //w <- x DIV y
    //Escreval(w) = 3
    
    //x <- 10
    //y <- 3
    //w <- x MOD y
    //w<- x % y
    //Escreval(w)
    Escreval("Escreva um Numero")
    Leia (x)
    
    se x MOD 2 = 0 entao
    Escreval("Esse Numero é Par")
    
    senao
    Escreval("Esse Numero é Impar")
    
    fimse
Fimalgoritmo