Algoritmo "Trabalhando com tipos"

Var
  palavraum,palavradois,palavratres: caractere
  numero1,numero2,numero3: inteiro

Inicio
  Escreval("Palavra 1: ")
  Leia(palavraum)
  Escreval("Palavra 2: ")
  Leia(palavradois)
  Escreval("Numero 1: ")
  Leia(numero1)
  Escreval("Numero 2: ")
  Leia(numero2)
  
  palavratres <- palavraum +" "+ palavradois
  numero3 <- numero1 + numero2
  Escreval(palavratres)
  Escreval(numero3)

Fimalgoritmo