Algoritmo "semnome"

Var
   voto: caractere
Inicio
      Escreval("Digite o Seu Voto: ")
      leia (voto)
escolha voto
caso "20"
     Escreval("voce votou em Marcelo Bernat")
                    caso "30"
                    Escreval("voce votou em Pernalonga")
                                   caso "40"
                                        Escreval("voce votou em Patolino")
outrocaso
         Escreval("Voto Nulo")

Fimalgoritmo